// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InvalidAutenticationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void invalidLogin() {
    driver.Navigate().GoToUrl("https://sso.a1.bg/oauth/2/login");
    driver.Manage().Window.Size = new System.Drawing.Size(1223, 658);
    driver.FindElement(By.CssSelector(".input-lineedit:nth-child(2)")).Click();
    driver.FindElement(By.Id("identifierId")).SendKeys("MaRiYa");
    driver.FindElement(By.CssSelector(".ZFr60d")).Click();
    driver.FindElement(By.CssSelector("#passwordNext > .CwaK9")).Click();
  }
}